# Generated by Django 4.2.18 on 2025-01-28 00:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=80, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('color', models.CharField(default='#666666', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('description_el', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=255)),
                ('license_plate', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bearing', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('trip_id', models.CharField(max_length=255)),
                ('route_id', models.CharField(max_length=255)),
                ('current_status', models.CharField(choices=[('INCOMING_AT', 'Approaching stop'), ('STOPPED_AT', 'Stopped at stop'), ('IN_TRANSIT', 'In transit')], max_length=20)),
                ('current_stop_sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle_id'], name='transit_rea_vehicle_e06ca4_idx'), models.Index(fields=['trip_id'], name='transit_rea_trip_id_565549_idx')],
            },
        ),
    ]
