# Generated by Django 4.2.18 on 2025-01-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.stop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='transit.RouteStop', to='transit.stop'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'sequence'], name='transit_rou_route_i_1d1243_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop'), ('route', 'sequence')},
        ),
    ]
