# Generated by Django 4.2.18 on 2025-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_routestop_route_stops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='direction',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='first_stop',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='holiday_afternoon_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='holiday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='holiday_morning_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='holiday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='holiday_trips',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='last_stop',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='line_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='route',
            name='saturday_afternoon_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='saturday_morning_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='saturday_trips',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='stops_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday_afternoon_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday_morning_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday_trips',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
