# Generated by Django 4.2.18 on 2025-01-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_route_direction_route_first_stop_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE transit_route ALTER COLUMN name DROP NOT NULL;",
            "ALTER TABLE transit_route ALTER COLUMN name SET NOT NULL;"
        ),
    ]
